name: Deployment

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: 'Init: Summon NodeJS'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Cache: node_modules"
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ env.cache-name }}-
            ${{ runner.OS }}-node-
      - name: 'Init: Install yarn'
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
      - name: 'Init: Install dependencies'
        run: |
          yarn install
      - name: 'Test: Type checking'
        run: |
          yarn test:types
      - name: 'Test: Code linting'
        run: |
          yarn test:lint
  deploy:
    needs: test
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: 'Init: Summon NodeJS'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Cache: node_modules"
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ env.cache-name }}-
            ${{ runner.OS }}-node-
      - name: "Cache: Gatsby builds"
        uses: actions/cache@v1
        with:
          path: .cache
          key: ${{ runner.OS }}-rayriffy-h-gatsby-${{ hashFiles('**/diskstore-*.*') }}
          restore-keys: |
            ${{ runner.OS }}-rayriffy-h-gatsby-${{ hashFiles('**/diskstore-*.*') }}
            ${{ runner.OS }}-rayriffy-h-gatsby-
      - name: 'Init: Install yarn'
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
      - name: 'Init: Install dependencies'
        run: |
          yarn install
      - name: "Build: Trigger build site"
        run: |
            yarn build
      - name: "Deploy: Upload to Netlify"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
            yarn deploy --message "Automatic deployment from GitHub Actions"
